Repository sous-chefs/grafana, pull requests merged in 2018-11, with the labels that each got.

#205 add amazon for platform_family [enhancement]
  CHANGELOG.md
  attributes/default.rb
  recipes/_install_file.rb
  recipes/_install_package.rb
Labels: enhancement

#203 Update to grafana 5.3.4
  .kitchen.dokken.yml
  .kitchen.yml
  CHANGELOG.md
  README.md
  attributes/default.rb
  metadata.rb
  spec/unit/default_spec.rb
  spec/unit/install_package_spec.rb
Labels: Priority: Medium

#206 Add Xorima to CodeOwners
  CODEOWNERS
Labels: Status: In Progress

#214 Remove Travis
  .circleci/config.yml
  .travis.yml
Labels: Priority: Low, Status: In Progress, Type: Documentation, Type: Maintenance
