Repository sous-chefs/grafana, pull requests merged in 2019-05, with the labels that each got.

#244 Accept Chef License
  .kitchen.dokken.yml
Labels: Maintenance

#242 Standardise Danger
  Dangerfile
Labels: Maintenance

#243 Readme Maintainers
  README.md
Labels: Maintenance

#246 Fix issue with oauth spelling
  CHANGELOG.md
  documentation/grafana_config_auth.md
  metadata.rb
  resources/config_auth.rb
Labels: Bug, Priority: High

#250 Add API resource support for proxy_auth
  CHANGELOG.md
  README.md
  documentation/grafana_dashboard.md
  documentation/grafana_datasource.md
  documentation/grafana_organization.md
  documentation/grafana_user.md
  libraries/api_helper.rb
  resources/dashboard.rb
  resources/datasource.rb
  resources/organization.rb
  resources/user.rb
Labels: Feature Request, In Progress, Waiting on Contributor

#259 enable circleci 2.0 orb testing
  .circleci/config.yml
  .github/lock.yml
  .kitchen.dokken.yml
  .mdlrc
  .rubocop.yml
  CHANGELOG.md
  documentation/grafana_config.md
  documentation/grafana_config_alerting.md
  documentation/grafana_config_auth.md
  documentation/grafana_config_dashboards.md
  documentation/grafana_config_database.md
  documentation/grafana_config_dataproxy.md
  documentation/grafana_config_emails.md
  documentation/grafana_config_enterprise.md
  documentation/grafana_config_explore.md
  documentation/grafana_config_external_image_storage_s3.md
  documentation/grafana_config_ldap.md
  documentation/grafana_config_ldap_group_mappings.md
  documentation/grafana_config_ldap_servers.md
  documentation/grafana_config_log.md
  documentation/grafana_config_metrics.md
  documentation/grafana_config_panels.md
  documentation/grafana_config_paths.md
  documentation/grafana_config_quota.md
  documentation/grafana_config_security.md
  documentation/grafana_config_server.md
  documentation/grafana_config_session.md
  documentation/grafana_config_smtp.md
  documentation/grafana_config_snapshots.md
  documentation/grafana_config_users.md
  documentation/grafana_dashboard.md
  documentation/grafana_datasource.md
  documentation/grafana_organization.md
  documentation/grafana_user.md
  kitchen.dokken.yml
  kitchen.yml
Labels: Maintenance, Tech Debt
