Repository sous-chefs/grafana, pull requests merged in 2020-06, with the labels that each got.

#363 Extended logging/min_refresh_interval
  CHANGELOG.md
  documentation/grafana_config_dashboards.md
  libraries/api_helper.rb
  resources/config_dashboards.rb
  templates/grafana.ini.erb
  test/fixtures/cookbooks/test/recipes/configure.rb
  test/integration/configure/configure_spec.rb
Labels: Feature Request, Release: Minor, Waiting on Contributor

#365 Add support for latest centos debian and amazon linux os
  .github/workflows/ci.yml
  CHANGELOG.md
  kitchen.dokken.yml
  kitchen.yml
Labels: Maintenance, Tech Debt

#364 Remove Chef Sleep from tests
  CHANGELOG.md
  test/integration/configure/configure_spec.rb
Labels: Maintenance, Tech Debt

#368 Missing readme entries
  README.md
Labels: Documentation
