Repository sous-chefs/grafana, pull requests merged in 2020-08, with the labels that each got.

#379 Add ability to use cookbook to only generate config file
  CHANGELOG.md
  documentation/grafana_config_writer.md
  resources/config_writer.rb
  spec/unit/config_spec.rb
Labels: Feature Request, Release: Minor

#377 Feature/support https and url_path_prefix
  CHANGELOG.md
  documentation/grafana_dashboard.md
  documentation/grafana_dashboard_template.md
  documentation/grafana_dashboards_backup.md
  documentation/grafana_datasorces_backup.md
  documentation/grafana_datasource.md
  documentation/grafana_folder.md
  documentation/grafana_organization.md
  documentation/grafana_user.md
  libraries/api_helper.rb
  libraries/user_api.rb
  resources/dashboard.rb
  resources/dashboard_template.rb
  resources/dashboards_backup.rb
  resources/datasource.rb
  resources/datasources_backup.rb
  resources/folder.rb
  resources/organization.rb
  resources/user.rb
Labels: Release: Minor

#382 Bugfix for undefined port variable (#381)
  CHANGELOG.md
  libraries/api_helper.rb
Labels: Bug, Release: Patch
